//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCResort.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class room
    {
        public int idRoom { get; set; }
        public int Employee_idEmployee { get; set; }
        public Nullable<int> NumOfRoom { get; set; }
        public Nullable<int> NumOfBeds { get; set; }
        public string Status { get; set; }
        public string Info { get; set; }
    
        public virtual employee employee { get; set; }
    }
}
