
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hotel2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Employee
{

    public Employee()
    {

        this.News = new HashSet<News>();

        this.Reservations = new HashSet<Reservation>();

        this.Rooms = new HashSet<Room>();

    }


    public int idEmplyee { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public Nullable<System.DateTime> DateOfBirth { get; set; }

    public string Type { get; set; }

    public Nullable<int> Salary { get; set; }



    public virtual ICollection<News> News { get; set; }

    public virtual ICollection<Reservation> Reservations { get; set; }

    public virtual ICollection<Room> Rooms { get; set; }

}

}
