
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Hotel2.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Guest
{

    public Guest()
    {

        this.Reservations = new HashSet<Reservation>();

    }


    public int idGuest { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public Nullable<System.DateTime> DateOfBirth { get; set; }

    public string CreditCardNum { get; set; }

    public Nullable<System.DateTime> DataOfExpiration { get; set; }



    public virtual ICollection<Reservation> Reservations { get; set; }

}

}
